version: '3'

services:
  sandbox:
    build: .
    restart: always
    ports:
      - "8080:8080"
    container_name: sandbox
    hostname: sandbox
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    container_name: mysql
    hostname: mysql
    volumes:
      - ./setup/mysql/conf.d:/etc/mysql/conf.d
      - ./setup/mysql/init:/docker-entrypoint-initdb.d
